=== sosy-lab/benchexec/benchmark-1.9.dtd
<!ELEMENT benchmark ((rundefinition | option | propertyfile | tasks | requiredfiles | resultfiles | require )*, columns?)>
<!ELEMENT rundefinition (tasks | option | propertyfile | requiredfiles)*>

<!ELEMENT tasks (include | includesfile | exclude | excludesfile | append | withoutfile | option | propertyfile | requiredfiles)*>
<!ELEMENT include (#PCDATA)>
<!ELEMENT includesfile (#PCDATA)>
<!ELEMENT exclude (#PCDATA)>
<!ELEMENT excludesfile (#PCDATA)>
<!ELEMENT withoutfile (#PCDATA)>
<!ELEMENT append (#PCDATA)>

<!ELEMENT requiredfiles (#PCDATA)>
<!ELEMENT resultfiles (#PCDATA)>
<!ELEMENT require (#PCDATA)>

<!ELEMENT option (#PCDATA)>
<!ELEMENT propertyfile (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>

<!ATTLIST rundefinition name CDATA #IMPLIED>

<!ATTLIST benchmark tool CDATA #REQUIRED>
<!ATTLIST benchmark memlimit CDATA #IMPLIED>
<!ATTLIST benchmark timelimit CDATA #IMPLIED>
<!ATTLIST benchmark hardtimelimit CDATA #IMPLIED>
<!ATTLIST benchmark cpuCores CDATA #IMPLIED>
<!ATTLIST benchmark threads CDATA #IMPLIED>

<!ATTLIST tasks name CDATA #IMPLIED>

<!ATTLIST require cpuModel CDATA #IMPLIED>
<!ATTLIST require cpuCores CDATA "1">
<!ATTLIST require memory   CDATA "1">

<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST column title CDATA #IMPLIED
                 numberOfDigits CDATA #IMPLIED>

=== sosy-lab/benchexec/doc/benchmark-example-rand.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark PUBLIC "+//IDN sosy-lab.org//DTD BenchExec benchmark 1.9//EN" "http://www.sosy-lab.org/benchexec/benchmark-1.9.dtd">
<!-- Example file for benchmark definition for BenchExec
     with dummy tool "rand" that simply returns random answers.
     No resource limits are specified. -->
<benchmark tool="rand">

  <!-- <rundefinition> defines a tool configuration to benchmark
       (tool rand does not need any arguments and has only one configuration). -->
  <rundefinition/>

  <!-- <tasks> defines a set of tasks:
       we define three sets of some arbitrary example files here. -->
  <tasks name="DTD files">
    <include>*.dtd</include>
  </tasks>

  <tasks name="Markdown files">
    <include>*.md</include>
  </tasks>

  <tasks name="XML files">
    <include>*.xml</include>
  </tasks>

  <!-- <tasks> with <withoutfile> allows to define tasks without input files,
       if the tool supports this. -->
  <tasks name="Dummy tasks">
    <withoutfile>dummy task 1</withoutfile>
    <withoutfile>dummy task 2</withoutfile>
    <withoutfile>dummy task 3</withoutfile>
  </tasks>
</benchmark>

=== sosy-lab/benchexec/doc/benchmark.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark PUBLIC "+//IDN sosy-lab.org//DTD BenchExec benchmark 1.9//EN" "http://www.sosy-lab.org/benchexec/benchmark-1.9.dtd">
<!-- Example file for benchmark definition for BenchExec. -->
<benchmark tool="*tool to benchmark (name of tool-info module for BenchExec)*"
           timelimit="*optional CPU time limit, use unit 's', 'min', etc. (default: none)*"
           hardtimelimit="*optional hard CPU time limit, use unit 's', 'min', etc. (tool will be forcefully killed, otherwise identical with timelimit)"
           memlimit="*optional memory limit, use unit 'B', 'kB', 'MB' etc. (default: none)*"
           cpuCores="*optional CPU core limit (default: none)*"
           threads="*optional number of parallel tool executions (default: 1)*">

  <!-- <rundefinition> defines a tool configuration to benchmark (can appear multiple times). -->
  <rundefinition name="*optional name for tool configuration*">

    <!-- <option> defines command-line arguments (can appear multiple times). -->
    <option name="*command-line argument for tool*">*optional value for command-line argument*</option>
  </rundefinition>

  <!-- <tasks> defines a set of tasks (can appear multiple times). -->
  <tasks name="*optional name for this subset of tasks*">
    <include>*file-name pattern for input files*</include>
    <includesfile>*file-name pattern for include files (text files with a pattern on each line)*</includesfile>
    <exclude>*file-name pattern for exclusion from input files*</exclude>
    <excludesfile>*file-name pattern for exclude files (text files with a pattern on each line)*</excludesfile>

    <!-- <withoutfile> allows to define a task that does not directly correspond to an input file.
         This can be used for example to define multiple tasks for the same input file but with different entry points. -->
    <withoutfile>*identifier of task*</withoutfile>

    <!-- <propertyfile> defines a property file with the specification to check (for software verification). -->
    <!-- <propertyfile>*file.prp*</propertyfile> -->

    <!-- <option> may be used here, too. -->
  </tasks>

  <columns>
    <!-- <column> tags may be used to define columns in the result tables with data from the tool output. -->
    <column title="*column title*">*pattern for extract data for this column from tool output*</column>
  </columns>

  <!-- <option> may be used here, too. -->
  <!-- <propertyfile> may be used here, too. -->

  <!-- Copy all result files from below the working directory to the output directory
       (this is redundant because it is the default). -->
  <resultfiles>.</resultfiles>

</benchmark>
